name: Test PostgreSQL migrations
on:
  push:
    branches: [main]

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: ai-chatbot-server-test
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'

      - name: Yarn install
        run: yarn install --frozen-lockfile

      # - name: Install PostgreSQL client
      #   run: |
      #     apt-get update
      #     apt-get install --yes postgresql-client

      - name: Setup database
        run: psql -h postgres -U postgres_user -c 'CREATE DATABASE "ai-chatbot-server-test";'
        env:
          PGPASSWORD: postgres

      - name: Run migration
        run: yarn update-db
